---

- hosts: apics
  gather_facts: no
  module_defaults:
    # Group defaults for collections are not available for ansible <2.12
    # and also cisco.aci doesn't define any groups anyway (yet).
    # While defining module defaults for every module being used exactly once is rather pointless
    # it makes the module code more readable and also things may change and this makes adapting easier.
    cisco.aci.aci_bd:
      host: "{{ inventory_hostname }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
    cisco.aci.aci_bd_subnet:
      host: "{{ inventory_hostname }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
    cisco.aci.aci_contract:
      host: "{{ inventory_hostname }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
    cisco.aci.aci_filter:
      host: "{{ inventory_hostname }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
    cisco.aci.aci_tenant:
      host: "{{ inventory_hostname }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
    cisco.aci.aci_vrf:
      host: "{{ inventory_hostname }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
  tasks:
    - name: Validate/Preprocess config input
      command: "./process_input.py {{ aci_config }}"
      register: aci_processed_config
      changed_when: False
      failed_when: "aci_processed_config.rc != 0"
      delegate_to: localhost

    - name: Register preprocessed config as fact
      set_fact:
        aci_fact_config: "{{ aci_processed_config.stdout }}"

    - name: Valid Config
      debug:
        var: aci_fact_config

    - name: Create Tenants
      cisco.aci.aci_tenant:
        name: "{{ item.tenant }}"
        description: "{{ item.description }}"
        state: present
      with_items: "{{ aci_fact_config.tenants }}"

    - name: Create VRFs
      cisco.aci.aci_vrf:
        name: "{{ item.vrf }}"
        tenant: "{{ item.tenant }}"
        state: present
      with_items: "{{ aci_fact_config.vrfs }}"

    - name: Create Filters
      cisco.aci.aci_filter:
        name: "{{ item.filter }}"
        tenant: "{{ item.tenant }}"
        state: present
      with_items: "{{ aci_fact_config.filters }}"

    - name: Create Contracts
      cisco.aci.aci_contract:
        name: "{{ item.contract }}"
        tenant: "{{ item.tenant }}"
        scope: "{{ item.scope }}"
        state: present
      with_items: "{{ aci_fact_config.contracts }}"

    - name: Create Bridge Domains
      cisco.aci.aci_bd:
        name: "{{ item.bd }}"
        tenant: "{{ item.tenant }}"
        vrf: "{{ item.vrf }}"
        state: present
      with_items: "{{ aci_fact_config.bridge_domains }}"

    - name: Create Bridge Domain Subnets
      cisco.aci.aci_bd_subnet:
        tenant: "{{ item.tenant }}"
        bd: "{{ item.bd }}"
        gateway: "{{ item.gateway }}"
        mask: "{{ item.mask }}"
        state: present
      with_items: "{{ aci_fact_config.bridge_domain_subnets }}"
