---

- hosts: apics
  gather_facts: no
  module_defaults:
    # Group defaults for collections are not available for ansible <=2.12
    # and also cisco.aci doesn't define any groups anyway (yet).
    # While defining module defaults for every module being used exactly once is rather pointless
    # it makes the module code more readable and also things may change and this makes adapting easier.
    cisco.aci.aci_tenant:
      host: "{{ inventory_hostname }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
  tasks:
    - name: Query current tenants
      cisco.aci.aci_tenant:
        state: query
      register: tenant_query

    - name: Query result
      debug:
        var: tenant_query
